# Generated by Django 4.2.3 on 2023-07-26 09:05

from django.db import migrations, models

# the migration class for creating the 'UserAddress' model.
class Migration(migrations.Migration):

    # Specify a dependency on a previous migration ('0001_initial') or other models.
    dependencies = [
        ('django_blog', '0001_initial'),
    ]

    operations = [
        # Create a new model named 'UserAddress' with following fields
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=10)),
                ('house_number', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
    ]
