# Generated by Django 4.2.3 on 2023-09-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraddress',
            table='UserAddress',
        ),
    ]
