# Generated by Django 4.2.3 on 2023-09-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0003_alter_useraddress_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraddress',
            table='django_blod_useraddress',
        ),
    ]
