# Generated by Django 4.2.3 on 2023-10-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0005_alter_useraddress_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('PercentageDownload', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table=None,
        ),
    ]
