# Generated by Django 4.2.1 on 2023-05-13 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

# migration class for creating the 'Post' model.
class Migration(migrations.Migration): 

    initial = True

    # Specify a dependency on the 'AUTH_USER_MODEL' setting, which typically represents the User model.
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL), 
    ]

    operations = [
        # Create a new model named 'Post'.
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                # A foreign key relationship with the User model representing the author of the post.
                # The 'on_delete' parameter specifies the behavior when the referenced user is deleted.
                # In this case, 'CASCADE' means that if the user is deleted, also delete the related posts.
            ],
        ),
    ]
