# Generated by Django 4.2.3 on 2023-12-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0006_progress_alter_useraddress_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='PercentageDownload',
        ),
        migrations.AddField(
            model_name='progress',
            name='April_2023',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='April_2024',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='August_2023',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='December_2023',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='Jan_2023',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
