class Cave:
    """回声洞"""
    def __init__(self, client): ...
    """随机获取回声"""
    async def get_cave(self): ...
    """传入回声"""
    async def insert_cave(self, qq: int, type: int, string: str, image: str = None): ...
    """更新回声"""
    async def update_cave(self, id: int, type: int, qq: int, string: str, image: str = None): ...
    """删除回声"""
    async def delete_cave(self, id: int): ...
    """恢复回声"""
    async def recover_cave(self, id: int): ...
    """获取指定 id 回声"""
    async def select_cave(self, id: int): ...
    """关键词随机获取回声"""
    async def random_keywords(self, keywords: str): ...
    """上传图片"""
    async def upload_image(self, url: str): ...

    @property
    def data(self) -> dict: ...
    @property
    def raw_code(self) -> int: ...
    @property
    def error(self) -> bool: ...