from logger_local.LoggerComponentEnum import LoggerComponentEnum

PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_ID = 178
PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_NAME = 'profile-zoominfo-graphql-imp-local-python-package/src/ZoomInfo.py'
PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_TYPE = LoggerComponentEnum.ComponentCategory.Code.value
PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE__COMPONENT_CATEGORY = LoggerComponentEnum.ComponentCategory.Code.value
DEVELOPER_EMAIL = 'sahar.g@circ.zone'

OBJECT_FOR_LOGGER_CODE = {
    'component_id': PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_ID,
    'component_name': PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_NAME,
    'component_category': PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_TYPE,
    'developer_email': DEVELOPER_EMAIL,
}

PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_NAME_TEST = 'profile-zoominfo-graphql-imp-local-python-package/tests/zoominfo_api_test.py'
PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_TYPE_TEST = LoggerComponentEnum.ComponentCategory.Unit_Test.value
PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_TESTING_FRAMEWORK_TEST = LoggerComponentEnum.testingFramework.pytest.value

OBJECT_FOR_LOGGER_CODE_TEST = {
    'component_id': PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_ID,
    'component_name': PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_NAME_TEST,
    'component_category': PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_COMPONENT_TYPE_TEST,
    'developer_email': DEVELOPER_EMAIL,
    'testing_framework': PROFILE_ZOOM_GRAPHQL_IMPORTER_LOCAL_PYTHON_PACKAGE_TESTING_FRAMEWORK_TEST
}
