# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models import AcceptSupplierInviteRequest
from ._models import ActiveWorkDto
from ._models import AddMesLink
from ._models import AddResourceTypeForNeedsGenerator
from ._models import AgentConfigDto
from ._models import AlertNotificationAccessDto
from ._models import AssetConsumptionDto
from ._models import AssetDto
from ._models import AssetDtoPagedResult
from ._models import AssetPowerDto
from ._models import AssetSimpleStructureDto
from ._models import AssetStructureDto
from ._models import AttachCalibrationCertificateRequest
from ._models import AttachPdfRequest
from ._models import AzureRegionDto
from ._models import BatchInsertValueRequest
from ._models import BatchInsertValuesResponseDto
from ._models import BookingDeliveryUpdateDto
from ._models import BookingItemRequestDto
from ._models import BookingItemResponseDto
from ._models import BookingRequestDto
from ._models import BookingRequestListDto
from ._models import BookingResponseDto
from ._models import BookingResponseListDto
from ._models import BookingUpdateDto
from ._models import CalculateBarWeight
from ._models import CalculateRightAngledTriangle
from ._models import CalculateSpindleAndCuttingSpeed
from ._models import CalibrationListToolDto
from ._models import CamTransferDto
from ._models import CdfConfigDto
from ._models import CncMachineCommunicationSettingsDto
from ._models import CncMachineDto
from ._models import CncMachineOperationDto
from ._models import CncMachineOperationSearchResultDto
from ._models import CncMachineOperationSearchResultDtoPagedResult
from ._models import CncMachineTransferDto
from ._models import CncPartDto
from ._models import CncPartListDto
from ._models import CncPartListDtoPagedResult
from ._models import CncProgramInfoDto
from ._models import CncSetupAuditDto
from ._models import CncToolDto
from ._models import CncToolSubTypeDto
from ._models import CncToolTypeDto
from ._models import CompanyCustomerDto
from ._models import CompanyDto
from ._models import CompanyUserDto
from ._models import ComponentSettingsDto
from ._models import ConsumptionDto
from ._models import CopyCncMachineOperationDto
from ._models import CopyCncMachineOperations
from ._models import CopyCncPart
from ._models import CopyToolsCncMachine
from ._models import CountryDto
from ._models import CreateAsset
from ._models import CreateCncMachine
from ._models import CreateCncMachineOperation
from ._models import CreateCncMachineOperationToolRequest
from ._models import CreateCncPart
from ._models import CreateCompanyUserRequest
from ._models import CreateCustomerMapping
from ._models import CreateCustomerOrderLineGhgReport
from ._models import CreateDocumentTypeRequest
from ._models import CreateElectricalIotConfig
from ._models import CreateLinkRequest
from ._models import CreateMachineGroup
from ._models import CreateMachineGroupResponse
from ._models import CreateMachineWithoutResource
from ._models import CreateMeasurementFormMapping
from ._models import CreateMeasurementFormSchema
from ._models import CreateMeasurementFormSchemaFeedbackRequest
from ._models import CreateMeasurementFormSchemaLinkRequest
from ._models import CreateMeasuringToolManufacturer
from ._models import CreateMeasuringToolRequest
from ._models import CreateMeasuringToolSubTypeRequest
from ._models import CreateMeasuringToolType
from ._models import CreateMeasuringUnit
from ._models import CreateMrb
from ._models import CreateMrbRevisionRequest
from ._models import CreateMrbTemplateRequest
from ._models import CreateResourceWithMachine
from ._models import CreateResourceWithoutMachine
from ._models import CreateSchemaElement
from ._models import CreateSupplierInvite
from ._models import CreateSupplierMapping
from ._models import CreateWorkOrderMapping
from ._models import CreateWorkspace
from ._models import CreateWorkspaceFromTemplate
from ._models import CreateWorkspaceTemplate
from ._models import CurrentCustomerDto
from ._models import CurrentWorkActivityDto
from ._models import CurrentWorkDto
from ._models import CustomerDto
from ._models import CustomerDtoPagedResult
from ._models import CustomerGroupDto
from ._models import CustomerOrderConsumptionRequest
from ._models import CustomerOrderDto
from ._models import CustomerOrderDtoPagedResult
from ._models import CustomerOrderInfoDto
from ._models import CustomerOrderLineDto
from ._models import CustomerOrderLineTraceItemDto
from ._models import CustomerOrderLineTraceStatusDto
from ._models import CustomerOrderLineWorkOrderTraceStatusNodeDto
from ._models import CustomerOrderTraceStatusDto
from ._models import DataHealthDto
from ._models import DeleteMrbTemplateRequest
from ._models import DeletePartDrawingRequest
from ._models import DepartmentDto
from ._models import DeprecateToolRequest
from ._models import DocumentGeneratorTypeDto
from ._models import DocumentLinkDto
from ._models import DocumentRevisionApprovalDto
from ._models import DocumentTagDto
from ._models import DocumentTypeDto
from ._models import DocumentTypeRuleDto
from ._models import DocumentTypeRuleTypeDto
from ._models import DownloadDto
from ._models import DrawingDto
from ._models import DrawingFileDto
from ._models import ElectricalIotConfigDto
from ._models import EmployeeDto
from ._models import ExportDimensionReportRequest
from ._models import ExternalRoleDto
from ._models import ExternalServiceCredentialDto
from ._models import ExternalSupplierDto
from ._models import FactoryUtilizationDto
from ._models import FileDto
from ._models import FilterValueWithQuantity
from ._models import FilterWorkorderOperationEvents
from ._models import GetAvailableProductionScheduleFiltersRequest
from ._models import GetConsumption
from ._models import GetPower
from ._models import ImageFileDto
from ._models import ImportDocument
from ._models import ImportDocumentResultDto
from ._models import ImportDocumentRevisionContentDto
from ._models import ImportDocumentRevisionDto
from ._models import ImportMeasurementFormInstanceRequest
from ._models import ImportMeasurementFormPartDto
from ._models import ImportMeasurementFormSchema
from ._models import ImportMeasurementSchemaInstanceDto
from ._models import ImportMeasuringTool
from ._models import ImportOperationWithTool
from ._models import ImportSupplier
from ._models import ImportSupplierUserDto
from ._models import ImportToolDto
from ._models import ImportedCalibration
from ._models import IncludeExcludeMrbRevisionContentRequest
from ._models import InventoryDto
from ._models import InviteDto
from ._models import IotTypeSourceDto
from ._models import LinkDto
from ._models import ListCncMachineOperationsRequest
from ._models import ListCncPartsRequest
from ._models import ListCustomerOrdersRequest
from ._models import ListCustomersRequest
from ._models import ListLinkableMeasurementFormSchemasRequest
from ._models import ListMachineUptimesTodayRequest
from ._models import ListMeasurementFormInstanceSchemaFeedbackRequest
from ._models import ListMeasurementFormNeedsRequest
from ._models import ListMeasurementFormSchemasNotNeededRequest
from ._models import ListMeasurementFormSchemasRequest
from ._models import ListMeasurementFormSchemasWithHistoryRequest
from ._models import ListMeasurementFormsByStatusRequest
from ._models import ListMeasurementFormsRequest
from ._models import ListMrbInstanceReportsRequest
from ._models import ListOrderScheduleRequest
from ._models import ListProductionScheduleOperationsRequest
from ._models import ListProjectsRequest
from ._models import ListTraceWorkordersRequest
from ._models import ListUsersRequest
from ._models import ListWorkOrdersRequest
from ._models import LocationDto
from ._models import Machine
from ._models import MachineAlarmCountDto
from ._models import MachineAlarmDetailsDto
from ._models import MachineAlarmDto
from ._models import MachineAlarmDtoPagedResult
from ._models import MachineAlarmSeverityOccurenceDto
from ._models import MachineAlarmSummaryDto
from ._models import MachineAlarmTimeserieDto
from ._models import MachineAlarmTimeseriesGroupDto
from ._models import MachineDataHealthDto
from ._models import MachineDto
from ._models import MachineErpDataDto
from ._models import MachineErpDataListDto
from ._models import MachineGroupDto
from ._models import MachineGroupMemberDto
from ._models import MachineGroupUtilizationDto
from ._models import MachineInactivityAlertTypeDto
from ._models import MachineInactivityCriteriaDto
from ._models import MachineInactivityCriteriaDtoAlertSubscriptionDto
from ._models import MachineStateDatapoint
from ._models import MachineStateDto
from ._models import MachineStateListDto
from ._models import MachineStatesSummaryDto
from ._models import MachineUptimeDto
from ._models import MachineUptimeSumDto
from ._models import MachineUptimesAggregateDto
from ._models import MachineUtilizationDto
from ._models import MachineUtilizationV2Dto
from ._models import ManufacturerDto
from ._models import MaterialConsumptionDto
from ._models import MaterialMassDensityDto
from ._models import MaterialPickListResultDto
from ._models import MaterialPickListResultEntryDto
from ._models import MaterialWeightDto
from ._models import MaterialsPrerequisiteDto
from ._models import MeasurementFormBalloonMappingDto
from ._models import MeasurementFormBalloonMappingRequestDto
from ._models import MeasurementFormCustomerSettingsDto
from ._models import MeasurementFormDto
from ._models import MeasurementFormElementDto
from ._models import MeasurementFormElementImportDto
from ._models import MeasurementFormElementValueAuditDto
from ._models import MeasurementFormElementValueDto
from ._models import MeasurementFormGroupedElementDto
from ._models import MeasurementFormImportLinkedSchemaDto
from ._models import MeasurementFormImportStatusDto
from ._models import MeasurementFormInstanceDto
from ._models import MeasurementFormInstanceDtoPagedResult
from ._models import MeasurementFormInstanceElementDto
from ._models import MeasurementFormInstanceFeedbackDto
from ._models import MeasurementFormInstanceOverviewDto
from ._models import MeasurementFormInstanceOverviewDtoPagedResult
from ._models import MeasurementFormInstanceProgressDto
from ._models import MeasurementFormInstanceSchemaDto
from ._models import MeasurementFormInstanceSchemaOverviewDto
from ._models import MeasurementFormInstanceSupplierDto
from ._models import MeasurementFormLinkedSchemaDto
from ._models import MeasurementFormListDto
from ._models import MeasurementFormListDtoPagedResult
from ._models import MeasurementFormMappingDto
from ._models import MeasurementFormMappingSuggestionDto
from ._models import MeasurementFormNeedDto
from ._models import MeasurementFormNeedDtoPagedResult
from ._models import MeasurementFormProgressDto
from ._models import MeasurementFormResourceTypeGeneratorDto
from ._models import MeasurementFormSchemaAttachmentDto
from ._models import MeasurementFormSchemaDto
from ._models import MeasurementFormSchemaNotNeededDto
from ._models import MeasurementFormSchemaNotNeededDtoPagedResult
from ._models import MeasurementFormSettingsDto
from ._models import MeasurementFormSupplierAccessInstanceDto
from ._models import MeasurementFormToolValueDto
from ._models import MeasurementFormVersionImportDto
from ._models import MeasurementFormWorkorderSchemaDto
from ._models import MeasurementFormWorkorderSequenceDto
from ._models import MeasurementFormWorkorderSupplierDto
from ._models import MeasurementFrequencyDto
from ._models import MeasuringToolCalibrationDto
from ._models import MeasuringToolCalibrationImportDto
from ._models import MeasuringToolDetailDto
from ._models import MeasuringToolDto
from ._models import MeasuringToolDtoPagedData
from ._models import MeasuringToolImportInformationDto
from ._models import MeasuringToolImportResultDto
from ._models import MeasuringToolSettingsDto
from ._models import MeasuringToolSubTypeDto
from ._models import MeasuringToolTypeDto
from ._models import MeasuringToolWhitelistDto
from ._models import MeasuringToolWhitelistDtoPagedData
from ._models import MeasuringUnitDto
from ._models import MesLinkDto
from ._models import MrbCompanySettingsDto
from ._models import MrbContentDto
from ._models import MrbContentItemDto
from ._models import MrbExtraDocumentDto
from ._models import MrbInstanceDto
from ._models import MrbInstanceJobDto
from ._models import MrbInstanceReportDto
from ._models import MrbInstanceReportDtoPagedResult
from ._models import MrbInstanceRevisionDto
from ._models import MrbPdfExportJobDto
from ._models import MrbSentInfoDto
from ._models import MrbStatusDto
from ._models import MrbTemplateDto
from ._models import MrbTemplateElementDto
from ._models import MrbTemplateElementIndexDto
from ._models import MrbTemplateTableOfContentsDto
from ._models import MrbTemplateUpdateElementDto
from ._models import NonConformanceDto
from ._models import NumericDataPointDto
from ._models import NumericNullableValueWithTimestamp
from ._models import OperationPrerequisitesDto
from ._models import OperationStatusFilterWithQuantity
from ._models import OperatorAndMachineDto
from ._models import OrderReferenceDto
from ._models import PartDto
from ._models import PickListMaterialLineDto
from ._models import PickListSuggestionDto
from ._models import PostMaterialPickListRequest
from ._models import PowerDto
from ._models import PowerOnUtilizationDto
from ._models import PowerOnUtilizationList
from ._models import PowerOnUtilizationV2Dto
from ._models import PowerRegionDto
from ._models import ProblemDetails
from ._models import ProductionCompanyDto
from ._models import ProductionOrderBomDto
from ._models import ProductionOrderDto
from ._models import ProductionOrderOperationActivityDto
from ._models import ProductionOrderOperationDto
from ._models import ProductionResourceDto
from ._models import ProductionScheduleFiltersDto
from ._models import ProductionScheduleOperationDto
from ._models import ProductionScheduleOperationDtoPagedResult
from ._models import ProgramFileDto
from ._models import RegisterMeasuringToolCalibrationRequest
from ._models import RegisterWorkorderOperationEventRequest
from ._models import ReportOperationProgress
from ._models import ReportOperationProgressDto
from ._models import ResourceDto
from ._models import ResourceExistDto
from ._models import ResourceGroupDto
from ._models import RightAngledTriangleDto
from ._models import SaveCommentRequest
from ._models import SaveMeasurementFormInstanceSchemaCommentRequest
from ._models import SaveToolRequest
from ._models import SaveValueRequest
from ._models import SaveValueResponseDto
from ._models import ScheduledWorkSummaryDto
from ._models import SchemaFeedbackCreatedDto
from ._models import SchemaFeedbackDto
from ._models import SchemaFeedbackDtoPagedResult
from ._models import SchemaInstanceElementDto
from ._models import SearchWorkOrderDto
from ._models import SelectProductionCompany
from ._models import SetIsBetaTesterRequest
from ._models import SetMeasurementFormMappingBalloonsRequest
from ._models import SetMeasurementFormNeedAsNotNeededRequest
from ._models import SetMeasurementFormNeedUserRequest
from ._models import SetMeasurementFormSchemaFeedbackUserRequest
from ._models import SetTransferStatusRequest
from ._models import SingleMachineErpDataListDto
from ._models import SpindleAndCuttingSpeedDto
from ._models import StartCamTransferToMachine
from ._models import StartCamTransferToMachineFromTempUpload
from ._models import StartOperationDto
from ._models import StartOperations
from ._models import StartWorkOperationRequest
from ._models import StateDto
from ._models import StopWorkOperationRequest
from ._models import StoppedWorkDto
from ._models import SubscribeToMachineInactivityAlerts
from ._models import SubscriberDto
from ._models import SupplierInviteDto
from ._models import SurroundingOperationDto
from ._models import SustainabilityCustomerOrderDto
from ._models import SustainabilityNodeDto
from ._models import SustainabilityNodeProcurementInfoDto
from ._models import SustainabilityPartInfoDto
from ._models import TraceDto
from ._models import TraceItemConsumptionDto
from ._models import TraceItemDto
from ._models import TraceListItemDto
from ._models import TraceMaterialDetailDto
from ._models import TraceWorkOrderListDto
from ._models import TraceWorkOrderListDtoPagedResult
from ._models import TrackingEventDto
from ._models import TrackingHistoryDto
from ._models import TrackingHistoryUpdateDto
from ._models import TrackingUpdateDto
from ._models import TrackingWorkOrderDto
from ._models import UnregisteredToolValueDto
from ._models import UpdateAssetRequest
from ._models import UpdateCdfConfig
from ._models import UpdateCncMachineCommunicationSettingsRequest
from ._models import UpdateCncMachineOperationRequest
from ._models import UpdateCncMachineOperationToolRequest
from ._models import UpdateCncMachineRequest
from ._models import UpdateCncMachineToolRequest
from ._models import UpdateCncPartRequest
from ._models import UpdateCompanyUserRequest
from ._models import UpdateDocumentTypeRequest
from ._models import UpdateDocumentTypeRuleRequest
from ._models import UpdateMachineGroup
from ._models import UpdateMachineInactivitySubscription
from ._models import UpdateMeasurementFormCustomerSettings
from ._models import UpdateMeasurementFormInstanceRequest
from ._models import UpdateMeasurementFormSchemaRequest
from ._models import UpdateMeasurementFormSettings
from ._models import UpdateMeasuringToolRequest
from ._models import UpdateMeasuringToolSettings
from ._models import UpdateMeasuringToolSubTypeRequest
from ._models import UpdateMeasuringToolTypeRequest
from ._models import UpdateMesLink
from ._models import UpdateMrbTemplate
from ._models import UpdateProgramFileRequest
from ._models import UpdateSchemaGroupedElementDto
from ._models import UpdateSchemaGroupedElementsRequest
from ._models import UpdateSchemaInstanceElementsRequest
from ._models import UpdateTraceManualCompletionRequest
from ._models import UpdateTraceRequest
from ._models import UpdateWhitelistedMeasuringTool
from ._models import UpdateWorkorderOperationEventTimestamps
from ._models import UpdateWorkspaceRequest
from ._models import UpdateWorkspaceWidgetSettingsRequest
from ._models import UpdateWorkspaceWidgetsRequest
from ._models import UploadCamFileDto
from ._models import UploadCamFileRequest
from ._models import UploadCncToolImageRequest
from ._models import UploadDrawingRequest
from ._models import UploadFileDto
from ._models import UploadFileRequest
from ._models import UploadInfoDto
from ._models import UploadPartDrawingRequest
from ._models import UploadRequest
from ._models import UpsertCustomerOrderRequest
from ._models import UpsertCustomerRequest
from ._models import UpsertMrbCompanySettings
from ._models import UpsertSupplierToMeasurementFormInstanceRequest
from ._models import UpsertWorkOrderConsumptionsRequest
from ._models import UpsertWorkOrderTracesRequest
from ._models import UpsertWorkorder
from ._models import UpsertWorkorderV2
from ._models import UptimeDowntimeDto
from ._models import UptimeDowntimesDto
from ._models import UserAppDto
from ._models import UserDetailsDto
from ._models import UserDto
from ._models import UserDtoPagedResult
from ._models import UtilizationDetailsDto
from ._models import UtilizationDto
from ._models import UtilizationListDto
from ._models import UtilizationSummaryDto
from ._models import UtilizationWorkorderDto
from ._models import ValidationRuleDto
from ._models import WarehouseLocationDto
from ._models import WhitelistMeasuringTool
from ._models import WorkOrderAttachmentDto
from ._models import WorkOrderConsumptionDto
from ._models import WorkOrderProjectDto
from ._models import WorkOrderProjectDtoPagedResult
from ._models import WorkOrderTraceItemDto
from ._models import WorkOrderTraceMaterialDto
from ._models import WorkOrderTraceOperationDto
from ._models import WorkerDto
from ._models import WorkorderCustomerOrderReferenceDto
from ._models import WorkorderDto
from ._models import WorkorderDtoPagedResult
from ._models import WorkorderHierarchyDto
from ._models import WorkorderImportTraceItemDto
from ._models import WorkorderListDto
from ._models import WorkorderListDtoPagedResult
from ._models import WorkorderMaterialDto
from ._models import WorkorderOperationDto
from ._models import WorkorderOperationEventDto
from ._models import WorkspaceDto
from ._models import WorkspaceListDto
from ._models import WorkspaceWidgetBreakpointDto
from ._models import WorkspaceWidgetDto

from ._enums import AlertNotificationAccessStatusDto
from ._enums import BonusType
from ._enums import BookingTypeDto
from ._enums import CalibrationListStatus
from ._enums import CalibrationStatusDto
from ._enums import CncFilterDeletedDto
from ._enums import CncOperationStatus
from ._enums import CustomerOrderLineStatus
from ._enums import CustomerOrderStatus
from ._enums import DocumentMetadataRequirement
from ._enums import DocumentNumberKey
from ._enums import DocumentRequirementStrategy
from ._enums import DocumentRuleType
from ._enums import DocumentSource
from ._enums import DocumentStatus
from ._enums import DocumentTypeCategory
from ._enums import DocumentTypeSearchOption
from ._enums import DocumentWorkflowType
from ._enums import EmptyChapterStrategy
from ._enums import ErrorCauseDto
from ._enums import ExternalServiceName
from ._enums import FileTransferDirection
from ._enums import FileTransferStatus
from ._enums import LocationKindDto
from ._enums import MachineAlarmType
from ._enums import MachineState
from ._enums import MaterialPickStatus
from ._enums import MaterialStatus
from ._enums import MaterialStatusDto
from ._enums import MeasurementFormInstanceStatus
from ._enums import MeasurementFormSource
from ._enums import MeasurementFormStatus
from ._enums import MeasurementFormValueType
from ._enums import MeasurementFrequency
from ._enums import MesLinkTypeDto
from ._enums import MrbElementType
from ._enums import MrbIndexContentType
from ._enums import MrbJobStatus
from ._enums import Mutability
from ._enums import NextOperationStatusDto
from ._enums import NonConformanceType
from ._enums import NotificationChannelDto
from ._enums import OperationStatusDto
from ._enums import OrderReferenceTypeDto
from ._enums import SchemaFeedbackStatus
from ._enums import SearchTypeDto
from ._enums import TraceIncludeStatus
from ._enums import TraceItemStatus
from ._enums import TraceStatus
from ._enums import TraceType
from ._enums import TrackingStatusDto
from ._enums import UploadStatusDto
from ._enums import WorkTypeDto
from ._enums import WorkorderStatus
from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "AcceptSupplierInviteRequest",
    "ActiveWorkDto",
    "AddMesLink",
    "AddResourceTypeForNeedsGenerator",
    "AgentConfigDto",
    "AlertNotificationAccessDto",
    "AssetConsumptionDto",
    "AssetDto",
    "AssetDtoPagedResult",
    "AssetPowerDto",
    "AssetSimpleStructureDto",
    "AssetStructureDto",
    "AttachCalibrationCertificateRequest",
    "AttachPdfRequest",
    "AzureRegionDto",
    "BatchInsertValueRequest",
    "BatchInsertValuesResponseDto",
    "BookingDeliveryUpdateDto",
    "BookingItemRequestDto",
    "BookingItemResponseDto",
    "BookingRequestDto",
    "BookingRequestListDto",
    "BookingResponseDto",
    "BookingResponseListDto",
    "BookingUpdateDto",
    "CalculateBarWeight",
    "CalculateRightAngledTriangle",
    "CalculateSpindleAndCuttingSpeed",
    "CalibrationListToolDto",
    "CamTransferDto",
    "CdfConfigDto",
    "CncMachineCommunicationSettingsDto",
    "CncMachineDto",
    "CncMachineOperationDto",
    "CncMachineOperationSearchResultDto",
    "CncMachineOperationSearchResultDtoPagedResult",
    "CncMachineTransferDto",
    "CncPartDto",
    "CncPartListDto",
    "CncPartListDtoPagedResult",
    "CncProgramInfoDto",
    "CncSetupAuditDto",
    "CncToolDto",
    "CncToolSubTypeDto",
    "CncToolTypeDto",
    "CompanyCustomerDto",
    "CompanyDto",
    "CompanyUserDto",
    "ComponentSettingsDto",
    "ConsumptionDto",
    "CopyCncMachineOperationDto",
    "CopyCncMachineOperations",
    "CopyCncPart",
    "CopyToolsCncMachine",
    "CountryDto",
    "CreateAsset",
    "CreateCncMachine",
    "CreateCncMachineOperation",
    "CreateCncMachineOperationToolRequest",
    "CreateCncPart",
    "CreateCompanyUserRequest",
    "CreateCustomerMapping",
    "CreateCustomerOrderLineGhgReport",
    "CreateDocumentTypeRequest",
    "CreateElectricalIotConfig",
    "CreateLinkRequest",
    "CreateMachineGroup",
    "CreateMachineGroupResponse",
    "CreateMachineWithoutResource",
    "CreateMeasurementFormMapping",
    "CreateMeasurementFormSchema",
    "CreateMeasurementFormSchemaFeedbackRequest",
    "CreateMeasurementFormSchemaLinkRequest",
    "CreateMeasuringToolManufacturer",
    "CreateMeasuringToolRequest",
    "CreateMeasuringToolSubTypeRequest",
    "CreateMeasuringToolType",
    "CreateMeasuringUnit",
    "CreateMrb",
    "CreateMrbRevisionRequest",
    "CreateMrbTemplateRequest",
    "CreateResourceWithMachine",
    "CreateResourceWithoutMachine",
    "CreateSchemaElement",
    "CreateSupplierInvite",
    "CreateSupplierMapping",
    "CreateWorkOrderMapping",
    "CreateWorkspace",
    "CreateWorkspaceFromTemplate",
    "CreateWorkspaceTemplate",
    "CurrentCustomerDto",
    "CurrentWorkActivityDto",
    "CurrentWorkDto",
    "CustomerDto",
    "CustomerDtoPagedResult",
    "CustomerGroupDto",
    "CustomerOrderConsumptionRequest",
    "CustomerOrderDto",
    "CustomerOrderDtoPagedResult",
    "CustomerOrderInfoDto",
    "CustomerOrderLineDto",
    "CustomerOrderLineTraceItemDto",
    "CustomerOrderLineTraceStatusDto",
    "CustomerOrderLineWorkOrderTraceStatusNodeDto",
    "CustomerOrderTraceStatusDto",
    "DataHealthDto",
    "DeleteMrbTemplateRequest",
    "DeletePartDrawingRequest",
    "DepartmentDto",
    "DeprecateToolRequest",
    "DocumentGeneratorTypeDto",
    "DocumentLinkDto",
    "DocumentRevisionApprovalDto",
    "DocumentTagDto",
    "DocumentTypeDto",
    "DocumentTypeRuleDto",
    "DocumentTypeRuleTypeDto",
    "DownloadDto",
    "DrawingDto",
    "DrawingFileDto",
    "ElectricalIotConfigDto",
    "EmployeeDto",
    "ExportDimensionReportRequest",
    "ExternalRoleDto",
    "ExternalServiceCredentialDto",
    "ExternalSupplierDto",
    "FactoryUtilizationDto",
    "FileDto",
    "FilterValueWithQuantity",
    "FilterWorkorderOperationEvents",
    "GetAvailableProductionScheduleFiltersRequest",
    "GetConsumption",
    "GetPower",
    "ImageFileDto",
    "ImportDocument",
    "ImportDocumentResultDto",
    "ImportDocumentRevisionContentDto",
    "ImportDocumentRevisionDto",
    "ImportMeasurementFormInstanceRequest",
    "ImportMeasurementFormPartDto",
    "ImportMeasurementFormSchema",
    "ImportMeasurementSchemaInstanceDto",
    "ImportMeasuringTool",
    "ImportOperationWithTool",
    "ImportSupplier",
    "ImportSupplierUserDto",
    "ImportToolDto",
    "ImportedCalibration",
    "IncludeExcludeMrbRevisionContentRequest",
    "InventoryDto",
    "InviteDto",
    "IotTypeSourceDto",
    "LinkDto",
    "ListCncMachineOperationsRequest",
    "ListCncPartsRequest",
    "ListCustomerOrdersRequest",
    "ListCustomersRequest",
    "ListLinkableMeasurementFormSchemasRequest",
    "ListMachineUptimesTodayRequest",
    "ListMeasurementFormInstanceSchemaFeedbackRequest",
    "ListMeasurementFormNeedsRequest",
    "ListMeasurementFormSchemasNotNeededRequest",
    "ListMeasurementFormSchemasRequest",
    "ListMeasurementFormSchemasWithHistoryRequest",
    "ListMeasurementFormsByStatusRequest",
    "ListMeasurementFormsRequest",
    "ListMrbInstanceReportsRequest",
    "ListOrderScheduleRequest",
    "ListProductionScheduleOperationsRequest",
    "ListProjectsRequest",
    "ListTraceWorkordersRequest",
    "ListUsersRequest",
    "ListWorkOrdersRequest",
    "LocationDto",
    "Machine",
    "MachineAlarmCountDto",
    "MachineAlarmDetailsDto",
    "MachineAlarmDto",
    "MachineAlarmDtoPagedResult",
    "MachineAlarmSeverityOccurenceDto",
    "MachineAlarmSummaryDto",
    "MachineAlarmTimeserieDto",
    "MachineAlarmTimeseriesGroupDto",
    "MachineDataHealthDto",
    "MachineDto",
    "MachineErpDataDto",
    "MachineErpDataListDto",
    "MachineGroupDto",
    "MachineGroupMemberDto",
    "MachineGroupUtilizationDto",
    "MachineInactivityAlertTypeDto",
    "MachineInactivityCriteriaDto",
    "MachineInactivityCriteriaDtoAlertSubscriptionDto",
    "MachineStateDatapoint",
    "MachineStateDto",
    "MachineStateListDto",
    "MachineStatesSummaryDto",
    "MachineUptimeDto",
    "MachineUptimeSumDto",
    "MachineUptimesAggregateDto",
    "MachineUtilizationDto",
    "MachineUtilizationV2Dto",
    "ManufacturerDto",
    "MaterialConsumptionDto",
    "MaterialMassDensityDto",
    "MaterialPickListResultDto",
    "MaterialPickListResultEntryDto",
    "MaterialWeightDto",
    "MaterialsPrerequisiteDto",
    "MeasurementFormBalloonMappingDto",
    "MeasurementFormBalloonMappingRequestDto",
    "MeasurementFormCustomerSettingsDto",
    "MeasurementFormDto",
    "MeasurementFormElementDto",
    "MeasurementFormElementImportDto",
    "MeasurementFormElementValueAuditDto",
    "MeasurementFormElementValueDto",
    "MeasurementFormGroupedElementDto",
    "MeasurementFormImportLinkedSchemaDto",
    "MeasurementFormImportStatusDto",
    "MeasurementFormInstanceDto",
    "MeasurementFormInstanceDtoPagedResult",
    "MeasurementFormInstanceElementDto",
    "MeasurementFormInstanceFeedbackDto",
    "MeasurementFormInstanceOverviewDto",
    "MeasurementFormInstanceOverviewDtoPagedResult",
    "MeasurementFormInstanceProgressDto",
    "MeasurementFormInstanceSchemaDto",
    "MeasurementFormInstanceSchemaOverviewDto",
    "MeasurementFormInstanceSupplierDto",
    "MeasurementFormLinkedSchemaDto",
    "MeasurementFormListDto",
    "MeasurementFormListDtoPagedResult",
    "MeasurementFormMappingDto",
    "MeasurementFormMappingSuggestionDto",
    "MeasurementFormNeedDto",
    "MeasurementFormNeedDtoPagedResult",
    "MeasurementFormProgressDto",
    "MeasurementFormResourceTypeGeneratorDto",
    "MeasurementFormSchemaAttachmentDto",
    "MeasurementFormSchemaDto",
    "MeasurementFormSchemaNotNeededDto",
    "MeasurementFormSchemaNotNeededDtoPagedResult",
    "MeasurementFormSettingsDto",
    "MeasurementFormSupplierAccessInstanceDto",
    "MeasurementFormToolValueDto",
    "MeasurementFormVersionImportDto",
    "MeasurementFormWorkorderSchemaDto",
    "MeasurementFormWorkorderSequenceDto",
    "MeasurementFormWorkorderSupplierDto",
    "MeasurementFrequencyDto",
    "MeasuringToolCalibrationDto",
    "MeasuringToolCalibrationImportDto",
    "MeasuringToolDetailDto",
    "MeasuringToolDto",
    "MeasuringToolDtoPagedData",
    "MeasuringToolImportInformationDto",
    "MeasuringToolImportResultDto",
    "MeasuringToolSettingsDto",
    "MeasuringToolSubTypeDto",
    "MeasuringToolTypeDto",
    "MeasuringToolWhitelistDto",
    "MeasuringToolWhitelistDtoPagedData",
    "MeasuringUnitDto",
    "MesLinkDto",
    "MrbCompanySettingsDto",
    "MrbContentDto",
    "MrbContentItemDto",
    "MrbExtraDocumentDto",
    "MrbInstanceDto",
    "MrbInstanceJobDto",
    "MrbInstanceReportDto",
    "MrbInstanceReportDtoPagedResult",
    "MrbInstanceRevisionDto",
    "MrbPdfExportJobDto",
    "MrbSentInfoDto",
    "MrbStatusDto",
    "MrbTemplateDto",
    "MrbTemplateElementDto",
    "MrbTemplateElementIndexDto",
    "MrbTemplateTableOfContentsDto",
    "MrbTemplateUpdateElementDto",
    "NonConformanceDto",
    "NumericDataPointDto",
    "NumericNullableValueWithTimestamp",
    "OperationPrerequisitesDto",
    "OperationStatusFilterWithQuantity",
    "OperatorAndMachineDto",
    "OrderReferenceDto",
    "PartDto",
    "PickListMaterialLineDto",
    "PickListSuggestionDto",
    "PostMaterialPickListRequest",
    "PowerDto",
    "PowerOnUtilizationDto",
    "PowerOnUtilizationList",
    "PowerOnUtilizationV2Dto",
    "PowerRegionDto",
    "ProblemDetails",
    "ProductionCompanyDto",
    "ProductionOrderBomDto",
    "ProductionOrderDto",
    "ProductionOrderOperationActivityDto",
    "ProductionOrderOperationDto",
    "ProductionResourceDto",
    "ProductionScheduleFiltersDto",
    "ProductionScheduleOperationDto",
    "ProductionScheduleOperationDtoPagedResult",
    "ProgramFileDto",
    "RegisterMeasuringToolCalibrationRequest",
    "RegisterWorkorderOperationEventRequest",
    "ReportOperationProgress",
    "ReportOperationProgressDto",
    "ResourceDto",
    "ResourceExistDto",
    "ResourceGroupDto",
    "RightAngledTriangleDto",
    "SaveCommentRequest",
    "SaveMeasurementFormInstanceSchemaCommentRequest",
    "SaveToolRequest",
    "SaveValueRequest",
    "SaveValueResponseDto",
    "ScheduledWorkSummaryDto",
    "SchemaFeedbackCreatedDto",
    "SchemaFeedbackDto",
    "SchemaFeedbackDtoPagedResult",
    "SchemaInstanceElementDto",
    "SearchWorkOrderDto",
    "SelectProductionCompany",
    "SetIsBetaTesterRequest",
    "SetMeasurementFormMappingBalloonsRequest",
    "SetMeasurementFormNeedAsNotNeededRequest",
    "SetMeasurementFormNeedUserRequest",
    "SetMeasurementFormSchemaFeedbackUserRequest",
    "SetTransferStatusRequest",
    "SingleMachineErpDataListDto",
    "SpindleAndCuttingSpeedDto",
    "StartCamTransferToMachine",
    "StartCamTransferToMachineFromTempUpload",
    "StartOperationDto",
    "StartOperations",
    "StartWorkOperationRequest",
    "StateDto",
    "StopWorkOperationRequest",
    "StoppedWorkDto",
    "SubscribeToMachineInactivityAlerts",
    "SubscriberDto",
    "SupplierInviteDto",
    "SurroundingOperationDto",
    "SustainabilityCustomerOrderDto",
    "SustainabilityNodeDto",
    "SustainabilityNodeProcurementInfoDto",
    "SustainabilityPartInfoDto",
    "TraceDto",
    "TraceItemConsumptionDto",
    "TraceItemDto",
    "TraceListItemDto",
    "TraceMaterialDetailDto",
    "TraceWorkOrderListDto",
    "TraceWorkOrderListDtoPagedResult",
    "TrackingEventDto",
    "TrackingHistoryDto",
    "TrackingHistoryUpdateDto",
    "TrackingUpdateDto",
    "TrackingWorkOrderDto",
    "UnregisteredToolValueDto",
    "UpdateAssetRequest",
    "UpdateCdfConfig",
    "UpdateCncMachineCommunicationSettingsRequest",
    "UpdateCncMachineOperationRequest",
    "UpdateCncMachineOperationToolRequest",
    "UpdateCncMachineRequest",
    "UpdateCncMachineToolRequest",
    "UpdateCncPartRequest",
    "UpdateCompanyUserRequest",
    "UpdateDocumentTypeRequest",
    "UpdateDocumentTypeRuleRequest",
    "UpdateMachineGroup",
    "UpdateMachineInactivitySubscription",
    "UpdateMeasurementFormCustomerSettings",
    "UpdateMeasurementFormInstanceRequest",
    "UpdateMeasurementFormSchemaRequest",
    "UpdateMeasurementFormSettings",
    "UpdateMeasuringToolRequest",
    "UpdateMeasuringToolSettings",
    "UpdateMeasuringToolSubTypeRequest",
    "UpdateMeasuringToolTypeRequest",
    "UpdateMesLink",
    "UpdateMrbTemplate",
    "UpdateProgramFileRequest",
    "UpdateSchemaGroupedElementDto",
    "UpdateSchemaGroupedElementsRequest",
    "UpdateSchemaInstanceElementsRequest",
    "UpdateTraceManualCompletionRequest",
    "UpdateTraceRequest",
    "UpdateWhitelistedMeasuringTool",
    "UpdateWorkorderOperationEventTimestamps",
    "UpdateWorkspaceRequest",
    "UpdateWorkspaceWidgetSettingsRequest",
    "UpdateWorkspaceWidgetsRequest",
    "UploadCamFileDto",
    "UploadCamFileRequest",
    "UploadCncToolImageRequest",
    "UploadDrawingRequest",
    "UploadFileDto",
    "UploadFileRequest",
    "UploadInfoDto",
    "UploadPartDrawingRequest",
    "UploadRequest",
    "UpsertCustomerOrderRequest",
    "UpsertCustomerRequest",
    "UpsertMrbCompanySettings",
    "UpsertSupplierToMeasurementFormInstanceRequest",
    "UpsertWorkOrderConsumptionsRequest",
    "UpsertWorkOrderTracesRequest",
    "UpsertWorkorder",
    "UpsertWorkorderV2",
    "UptimeDowntimeDto",
    "UptimeDowntimesDto",
    "UserAppDto",
    "UserDetailsDto",
    "UserDto",
    "UserDtoPagedResult",
    "UtilizationDetailsDto",
    "UtilizationDto",
    "UtilizationListDto",
    "UtilizationSummaryDto",
    "UtilizationWorkorderDto",
    "ValidationRuleDto",
    "WarehouseLocationDto",
    "WhitelistMeasuringTool",
    "WorkOrderAttachmentDto",
    "WorkOrderConsumptionDto",
    "WorkOrderProjectDto",
    "WorkOrderProjectDtoPagedResult",
    "WorkOrderTraceItemDto",
    "WorkOrderTraceMaterialDto",
    "WorkOrderTraceOperationDto",
    "WorkerDto",
    "WorkorderCustomerOrderReferenceDto",
    "WorkorderDto",
    "WorkorderDtoPagedResult",
    "WorkorderHierarchyDto",
    "WorkorderImportTraceItemDto",
    "WorkorderListDto",
    "WorkorderListDtoPagedResult",
    "WorkorderMaterialDto",
    "WorkorderOperationDto",
    "WorkorderOperationEventDto",
    "WorkspaceDto",
    "WorkspaceListDto",
    "WorkspaceWidgetBreakpointDto",
    "WorkspaceWidgetDto",
    "AlertNotificationAccessStatusDto",
    "BonusType",
    "BookingTypeDto",
    "CalibrationListStatus",
    "CalibrationStatusDto",
    "CncFilterDeletedDto",
    "CncOperationStatus",
    "CustomerOrderLineStatus",
    "CustomerOrderStatus",
    "DocumentMetadataRequirement",
    "DocumentNumberKey",
    "DocumentRequirementStrategy",
    "DocumentRuleType",
    "DocumentSource",
    "DocumentStatus",
    "DocumentTypeCategory",
    "DocumentTypeSearchOption",
    "DocumentWorkflowType",
    "EmptyChapterStrategy",
    "ErrorCauseDto",
    "ExternalServiceName",
    "FileTransferDirection",
    "FileTransferStatus",
    "LocationKindDto",
    "MachineAlarmType",
    "MachineState",
    "MaterialPickStatus",
    "MaterialStatus",
    "MaterialStatusDto",
    "MeasurementFormInstanceStatus",
    "MeasurementFormSource",
    "MeasurementFormStatus",
    "MeasurementFormValueType",
    "MeasurementFrequency",
    "MesLinkTypeDto",
    "MrbElementType",
    "MrbIndexContentType",
    "MrbJobStatus",
    "Mutability",
    "NextOperationStatusDto",
    "NonConformanceType",
    "NotificationChannelDto",
    "OperationStatusDto",
    "OrderReferenceTypeDto",
    "SchemaFeedbackStatus",
    "SearchTypeDto",
    "TraceIncludeStatus",
    "TraceItemStatus",
    "TraceStatus",
    "TraceType",
    "TrackingStatusDto",
    "UploadStatusDto",
    "WorkTypeDto",
    "WorkorderStatus",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
