"""
a simple class to manage/output messages generated by c8 'validation' modules
"""
__author__ = "(AA)"
__copyright__ = "C8"


from c8utils.fgcolors import fgcolors

class Message:
    '''
    ansible validation plugin message 
    '''
    OK = 1
    ERROR = 2
    WARNING = 4

    def __init__(self, level, msg, bold = False):
        self.level = level
        self.msg = msg 
        self.bold = bold 

    def __str__(self):
        ret = ""
        if self.bold:
            ret = fgcolors.BOLD 

        if self.level == Message.OK:
            ret += fgcolors.OK + " {:<10}".format("[OK]")
        elif self.level == Message.ERROR:
            ret += fgcolors.ERROR + " {:<10}".format("[ERR]")
        elif self.level == Message.WARNING:
            ret += fgcolors.WARNING + " {:<10}".format("[WARN]")

        ret += "{:<80}".format(self.msg) 
        ret += fgcolors.ENDC

        return ret
