
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-23T19:00:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e14e74e986270ebb5ed96391a13632a3bfaa777f",
 "version": "2024.5.23.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
