# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02.system.decorator.ipynb.

# %% auto 0
__all__ = ['prepend_string_arg']

# %% ../../nbs/02.system.decorator.ipynb 3
import functools

# %% ../../nbs/02.system.decorator.ipynb 4
def prepend_string_arg(str_arg="TQD_trqTrqSetNormal_MAP_v"):
    """
    function decorator to prepend a string argument to a     function

    Parameters:

        str_arg (str): string argument to prepend

    Return:

            function: decorated function
    """

    def decorate(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            __name__ = func.__name__
            __doc__ = func.__doc__
            return func(str_arg, *args, **kwargs)

        return wrapper

    return decorate
