
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-07T14:26:23-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "33d9d9dfb0e5c9c3b169f90d2a342865bdae2d94",
 "version": "1.9.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
