# Generated by Django 4.2.13 on 2024-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_cefran", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="djangocefranconfig",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "French")],
                default="fr",
                help_text="Only one configuration is allowed per language",
                max_length=7,
                verbose_name="Language",
            ),
        ),
    ]
