
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-24T17:08:32+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e76fdc48e94a50e63b1c1b5bd61e35c80e6b52fc",
 "version": "0.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
