
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-23T12:26:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae70a5e268933464f1c27664b2db999e45887d80",
 "version": "1.24.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
