query_to_create_one_pager_data_table = """
create table data_team.one_pager_data(
   table_unique_id int identity(0, 1),
   org_id varchar(80),
   cohort_year int,
   student_type varchar(40), 
   entry_term varchar(40),
   num_comm_match_inquired int,
  num_comm_match_applied int,
  num_comm_match_accepted int,
  num_comm_match_committed int,
  num_comm_match_enrolled int,
  num_preinq_inquired int,
  num_preinq_applied int,
  num_preinq_accepted int,
  num_preinq_committed int,
  num_preinq_enrolled int,
  num_organic_inquired int,
  num_organic_applied int,
  num_organic_accepted int,
  num_organic_committed int,
  num_organic_enrolled int,
  num_nondupe_ntr_inquired int,
  num_nondupe_ntr_applied int,
  num_nondupe_ntr_accepted int,
  num_nondupe_ntr_committed int,
  num_nondupe_ntr_enrolled int,
  community_funnel_inquired int,
  community_funnel_applied int,
  community_funnel_accepted int,
  community_funnel_committed int,
  community_funnel_enrolled int,
  per_comm_match_inquired numeric(6,4),
  per_comm_match_applied numeric(6,4),
  per_comm_match_accepted numeric(6,4),
  per_comm_match_committed numeric(6,4),
  per_comm_match_enrolled numeric(6,4),
  per_preinq_inquired numeric(6,4),
  per_preinq_applied numeric(6,4),
  per_preinq_accepted numeric(6,4),
  per_preinq_committed numeric(6,4),
  per_preinq_enrolled numeric(6,4),
  per_organic_inquired numeric(6,4),
  per_organic_applied numeric(6,4),
  per_organic_accepted numeric(6,4),
  per_organic_committed numeric(6,4),
  per_organic_enrolled numeric(6,4),
  per_nondupe_ntr_inquired numeric(6,4),
  per_nondupe_ntr_applied numeric(6,4),
  per_nondupe_ntr_accepted numeric(6,4),
  per_nondupe_ntr_committed numeric(6,4),
  per_nondupe_ntr_enrolled numeric(6,4),
  primary key(table_unique_id) )
  sortkey (org_id)
"""
