"""
    Emil Payment Service

    This service directly communicates with the various Payment Service Providers (PSPs)    in order to charge or refund customers. This service will automatically connect to the PSP linked   in your admin configuration; meaning if you configured Stripe, it will automatically create a payment   on Stripe when you create it in Emil.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import unittest

import eis.payments
from eis.payments.api.bank_accounts_api import BankAccountsApi  # noqa: E501


class TestBankAccountsApi(unittest.TestCase):
    """BankAccountsApi unit test stubs"""

    def setUp(self):
        self.api = BankAccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_bank_account(self):
        """Test case for create_bank_account

        Create a bank account  # noqa: E501
        """
        pass

    def test_list_bank_accounts(self):
        """Test case for list_bank_accounts

        List bank accounts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
