depends = ('ITKPyBase', 'ITKTransform', 'ITKRegistrationMethodsv4', 'ITKImageLabel', 'ITKImageGrid', 'ITKIOTransformBase', 'ITKIOImageBase', 'ITKCommon', 'ITKBinaryMathematicalMorphology', )
templates = (  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >, float'),
)
factories = ()
