# coding: utf-8
# Generated by setup.py for PyCBC on 2024-05-28 20:22:02 +0000.

# general info
version = '2.3.7'
date = '2024-05-28 20:15:34 +0000'
release = 'True'
last_release = '2.4.0'

# git info
git_hash = '2e0f835b436827ce1626c53bad647a96ced7e9d0'
git_branch = 'None'
git_tag = 'v2.3.7'
git_author = 'Ian Harry <ian.harry@ligo.org>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <>'
git_build_date = '2024-05-28 20:22:02 +0000'
git_verbose_msg = """Version: 2.3.7
Branch: None
Tag: v2.3.7
Id: 2e0f835b436827ce1626c53bad647a96ced7e9d0
Builder: Unknown User <>
Build date: 2024-05-28 20:22:02 +0000
Repository status is CLEAN: All modifications committed"""

from pycbc._version import *
