from .plot_module import SIZE_SMALL as SIZE_SMALL, latexify as latexify, savefig as savefig
from dataclasses import dataclass

@dataclass
class enable_latexify:
    enable: bool = ...
    width_scale_factor: float = ...
    height_scale_factor: float = ...
    fig_width: float | None = ...
    fig_height: float | None = ...
    font_size: int = ...
    legend_size = ...
    def __post_init__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args) -> None: ...
    def savefig(self, filename, despine: bool = True, fig_dir: str = 'tests/plot', **kwargs): ...
    def __init__(self, enable=..., width_scale_factor=..., height_scale_factor=..., fig_width=..., fig_height=..., font_size=...) -> None: ...
