class Statistics:
    """统计数据"""
    def __init__(self, client): ...
    """调用统计"""
    async def update_statistics(self, group_id: int, type: str): ...

    @property
    def data(self) -> dict: ...
    @property
    def raw_code(self) -> int: ...
    @property
    def error(self) -> bool: ...