
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-24T10:13:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8cb18c47d653f7375bf521021d3af589a89a327",
 "version": "2.37.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
