# Generated by Django 4.2.11 on 2024-05-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_fastoche",
            "0008_alter_fastochesocialmedia_options_fastocheconfig_language_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fastocheconfig",
            name="footer_brand",
            field=models.CharField(
                blank=True,
                default="République française",
                max_length=200,
                verbose_name="Institution (footer)",
            ),
        ),
        migrations.AlterField(
            model_name="fastocheconfig",
            name="footer_brand_html",
            field=models.CharField(
                blank=True,
                default="République<br />française",
                max_length=200,
                verbose_name="Institution with line break (footer)",
            ),
        ),
        migrations.AlterField(
            model_name="fastocheconfig",
            name="header_brand",
            field=models.CharField(
                blank=True,
                default="République française",
                max_length=200,
                verbose_name="Institution (header)",
            ),
        ),
        migrations.AlterField(
            model_name="fastocheconfig",
            name="header_brand_html",
            field=models.CharField(
                blank=True,
                default="République<br />française",
                max_length=200,
                verbose_name="Institution with line break (header)",
            ),
        ),
    ]
