from setuptools import setup, find_packages

setup(
    name='mypystarter',
    version='0.1.0',
    packages=find_packages(),
    include_package_data=True,
    license='MIT License',
    description='A Django JumpStart Library.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/jadliaissam/PyStarterV2',
    author='JADLI AISSAM',
    author_email='jadliaissam@gmail.com',
    classifiers=[
        'Environment :: Web Environment',
        'Framework :: Django',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
    ],
    install_requires=open('requirements.txt').read().splitlines(),
)
