
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-24T11:52:29-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "420909968ac2d91d6c2ba050ea1c689f38fe8002",
 "version": "v1.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
