"""constants"""

FILESYSTEM_CSV = "FILESYSTEM_CSV"
FILESYSTEM_PARQUET = "FILESYSTEM_PARQUET"
GOOGLE_CLOUD_PLATFORM_CLOUDSTORAGE_CSV = "GOOGLE_CLOUD_PLATFORM_CLOUDSTORAGE_CSV"
GOOGLE_CLOUD_PLATFORM_CLOUDSTORAGE_PARQUET = (
    "GOOGLE_CLOUD_PLATFORM_CLOUDSTORAGE_PARQUET"
)
SQL = "SQL"
