
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-24T16:46:11+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "77e79f863daf9aa0bc6b9e8bf5e6d74e14bd5367",
 "version": "0.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
