# Generated by Django 5.0.6 on 2024-05-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='base_dir',
            field=models.CharField(default='downloads', max_length=255),
        ),
    ]
