# Generated by Django 5.0.6 on 2024-05-21 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0008_alter_dataset_dataset_alter_dataset_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100)),
                ('column_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QueryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_name', models.CharField(max_length=100)),
                ('columns', models.ManyToManyField(related_name='query_columns', to='nhanes.querycolumns')),
            ],
        ),
        migrations.CreateModel(
            name='QueryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(choices=[('field_id', 'Field ID'), ('field_name', 'Field Name'), ('field_description', 'Field Description'), ('field_internal', 'Field Internal ID'), ('cycle', 'Cycle'), ('group', 'Group'), ('dataset_id', 'Dataset ID'), ('dataset_name', 'Dataset Name')], default='field_id', max_length=20)),
                ('operator', models.CharField(choices=[('lt', 'Less than'), ('lte', 'Less than or equal'), ('eq', 'Equal'), ('ne', 'Not equal'), ('gte', 'Greater than or equal'), ('gt', 'Greater than'), ('icontains', '...')], default='eq', max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('query_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='nhanes.querystructure')),
            ],
        ),
    ]
