# Generated by Django 5.0.6 on 2024-05-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0011_alter_queryfilter_filter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='querystructure',
            name='no_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='querystructure',
            name='no_multi_index',
            field=models.BooleanField(default=False),
        ),
    ]
