# Generated by Django 5.0.6 on 2024-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0012_querystructure_no_conflict_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryfilter',
            name='operator',
            field=models.CharField(choices=[('eq', 'Equal'), ('ne', 'Not Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('contains', 'Contains'), ('icontains', 'Contains (Case-Insensitive)'), ('exact', 'Exact'), ('iexact', 'Exact (Case-Insensitive)'), ('in', 'In'), ('startswith', 'Starts With'), ('istartswith', 'Starts With (Case-Insensitive)'), ('endswith', 'Ends With'), ('iendswith', 'Ends With (Case-Insensitive)'), ('isnull', 'Search For Null Values'), ('search', 'Search'), ('regex', 'Use Regular Expression'), ('iregex', 'Use Regular Expression (Case-Insensitive)')], default='eq', max_length=20),
        ),
    ]
