# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rebac/v1/check.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from rebac.v1 import relationships_pb2 as rebac_dot_v1_dot_relationships__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14rebac/v1/check.proto\x12\x0c\x61pi.rebac.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1crebac/v1/relationships.proto\"\x80\x01\n\x0c\x43heckRequest\x12-\n\x06object\x18\x01 \x01(\x0b\x32\x1d.api.rebac.v1.ObjectReference\x12\x10\n\x08relation\x18\x02 \x01(\t\x12/\n\x07subject\x18\x03 \x01(\x0b\x32\x1e.api.rebac.v1.SubjectReference\"\x8e\x01\n\rCheckResponse\x12\x34\n\x07\x61llowed\x18\x01 \x01(\x0e\x32#.api.rebac.v1.CheckResponse.Allowed\"G\n\x07\x41llowed\x12\x17\n\x13\x41LLOWED_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x41LLOWED_TRUE\x10\x01\x12\x11\n\rALLOWED_FALSE\x10\x02\x32_\n\x05\x43heck\x12V\n\x05\x43heck\x12\x1a.api.rebac.v1.CheckRequest\x1a\x1b.api.rebac.v1.CheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\"\t/v1/check:\x01*B,\n\x0c\x61pi.rebac.v1P\x01Z\x1a\x63iam-rebac/api/rebac/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rebac.v1.check_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014api.rebac.v1P\001Z\032ciam-rebac/api/rebac/v1;v1'
  _globals['_CHECK'].methods_by_name['Check']._options = None
  _globals['_CHECK'].methods_by_name['Check']._serialized_options = b'\202\323\344\223\002\016\"\t/v1/check:\001*'
  _globals['_CHECKREQUEST']._serialized_start=99
  _globals['_CHECKREQUEST']._serialized_end=227
  _globals['_CHECKRESPONSE']._serialized_start=230
  _globals['_CHECKRESPONSE']._serialized_end=372
  _globals['_CHECKRESPONSE_ALLOWED']._serialized_start=301
  _globals['_CHECKRESPONSE_ALLOWED']._serialized_end=372
  _globals['_CHECK']._serialized_start=374
  _globals['_CHECK']._serialized_end=469
# @@protoc_insertion_point(module_scope)
