# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: frequenz/api/microgrid/grid.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Metadata(betterproto.Message):
    """The grid connection point metadata."""

    rated_fuse_current: int = betterproto.uint32_field(1)
    """
    This refers to the maximum amount of electrical current, in amperes, that a
    fuse at the grid connection point is designed to safely carry under normal
    operating conditions. This limit applies to currents both flowing in or out
    of each of the 3 phases individually. In other words, a current _i_ A at
    one of the phases of the grid connection point must comply with the
    following constraint: `-rated_fuse_current <= i <= rated_fuse_current`
    """
