# Generated by Django 5.0.3 on 2024-05-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_modalds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type1',
            name='h2',
            field=models.CharField(help_text='줄넘기기 : br tag, 강조 : span tag', max_length=100, verbose_name='h2'),
        ),
        migrations.AlterField(
            model_name='type1',
            name='link_text',
            field=models.CharField(default='Get Started', max_length=50, verbose_name='link_text'),
        ),
        migrations.AlterField(
            model_name='type1',
            name='modal_title',
            field=models.CharField(blank=True, default='EVENT', max_length=50, verbose_name='modal_title'),
        ),
        migrations.AlterField(
            model_name='type2',
            name='h2',
            field=models.CharField(max_length=100, verbose_name='h2'),
        ),
        migrations.AlterField(
            model_name='type2',
            name='link_text',
            field=models.CharField(default='Get Started', max_length=50, verbose_name='link_text'),
        ),
        migrations.AlterField(
            model_name='type2',
            name='link_video_text',
            field=models.CharField(default='Watch Video', max_length=50, verbose_name='link_video_text'),
        ),
        migrations.AlterField(
            model_name='type2',
            name='modal_title',
            field=models.CharField(blank=True, default='EVENT', max_length=50, verbose_name='modal_title'),
        ),
        migrations.AlterField(
            model_name='type3',
            name='h2',
            field=models.CharField(help_text='줄넘기기 : br tag', max_length=100, verbose_name='h2'),
        ),
        migrations.AlterField(
            model_name='type3',
            name='link_text',
            field=models.CharField(default='Book a Table', max_length=50, verbose_name='link_text'),
        ),
        migrations.AlterField(
            model_name='type3',
            name='link_video_text',
            field=models.CharField(default='Watch Video', max_length=50, verbose_name='link_video_text'),
        ),
        migrations.AlterField(
            model_name='type3',
            name='modal_title',
            field=models.CharField(blank=True, default='EVENT', max_length=50, verbose_name='modal_title'),
        ),
        migrations.AlterField(
            model_name='type4',
            name='h1',
            field=models.CharField(max_length=100, verbose_name='h1'),
        ),
        migrations.AlterField(
            model_name='type4',
            name='h3',
            field=models.CharField(help_text='강조 : strong tag', max_length=50, verbose_name='h3'),
        ),
        migrations.AlterField(
            model_name='type4',
            name='link_text',
            field=models.CharField(default='Get Started', max_length=50, verbose_name='link_text'),
        ),
        migrations.AlterField(
            model_name='type4',
            name='modal_title',
            field=models.CharField(blank=True, default='EVENT', max_length=50, verbose_name='modal_title'),
        ),
        migrations.AlterField(
            model_name='type5',
            name='modal_title',
            field=models.CharField(blank=True, default='NOTI', max_length=50, verbose_name='modal_title'),
        ),
    ]
