
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-27T20:01:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6bf1bab747b81a2b1f02605139a1ea4af57bbb5",
 "version": "2024.5.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
