
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-28T16:55:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ff6a6454ab8f22e6d9dd32a0a678b5df5489555",
 "version": "2.3.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
