
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-23T14:05:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "60bddaeb8f4cc39eecb537c88a870a598a63301d",
 "version": "2024.5.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
