# '.model.py'
VAL_RATIO = 0.1
DROPOUT = 0.2
SEGMENT_LENGTH = 32
RNN_SIZE = 128
NUM_LAYERS = 3
BATCH_SIZE = 2048
EPOCHS = 100

# 'harmonizor.py'
RHYTHM_DENSITY = 0.9
CHORD_PER_BAR = True
REPEAT_CHORD = False