
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-27T19:31:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa97fa02467f0bc017c64041bde1735a35885eeb",
 "version": "2024.5.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
