# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02.system.exception.ipynb.

# %% auto 0
__all__ = ['ReadOnlyError', 'WriteOnlyError', 'TruckIDError']

# %% ../../nbs/02.system.exception.ipynb 3
class ReadOnlyError(Exception):
    pass

# %% ../../nbs/02.system.exception.ipynb 4
class WriteOnlyError(Exception):
    pass

# %% ../../nbs/02.system.exception.ipynb 5
class TruckIDError(Exception):
    pass
