class Bangumi:
    """番剧搜索"""
    def __init__(self, client): ...
    """搜索"""
    async def subject_search(self, keyword: str): ...

    @property
    def data(self) -> dict: ...
    @property
    def raw_code(self) -> int: ...
    @property
    def error(self) -> bool: ...