# Generated by Django 4.2.11 on 2024-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_fastoche", "0009_alter_fastocheconfig_footer_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fastocheconfig",
            name="footer_brand",
            field=models.CharField(
                blank=True,
                default="Web Fastoche",
                max_length=200,
                verbose_name="Institution (footer)",
            ),
        ),
        migrations.AlterField(
            model_name="fastocheconfig",
            name="footer_brand_html",
            field=models.CharField(
                blank=True,
                default="Web<br />Fastoche",
                max_length=200,
                verbose_name="Institution with line break (footer)",
            ),
        ),
        migrations.AlterField(
            model_name="fastocheconfig",
            name="header_brand",
            field=models.CharField(
                blank=True,
                default="Web Fastoche",
                max_length=200,
                verbose_name="Institution (header)",
            ),
        ),
        migrations.AlterField(
            model_name="fastocheconfig",
            name="header_brand_html",
            field=models.CharField(
                blank=True,
                default="Web<br />Fastoche",
                max_length=200,
                verbose_name="Institution with line break (header)",
            ),
        ),
    ]
