# Generated by Django 5.0.3 on 2024-03-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_title', models.CharField(blank=True, default='EVENT', max_length=20, verbose_name='modal_title')),
                ('h2', models.CharField(help_text='줄넘기기 : br tag, 강조 : span tag', max_length=40, verbose_name='h2')),
                ('p', models.TextField(help_text='줄넘기기 : br tag', verbose_name='p')),
                ('link_url', models.CharField(blank=True, help_text='공란 가능', max_length=1200, verbose_name='link_url')),
                ('link_text', models.CharField(default='Get Started', max_length=20, verbose_name='link_text')),
                ('bg', models.ImageField(upload_to='images/popup/type1')),
                ('bg2', models.ImageField(blank=True, upload_to='images/popup/type1')),
                ('bg3', models.ImageField(blank=True, upload_to='images/popup/type1')),
                ('activate', models.BooleanField(default=False, help_text='활성창 1개만 가능')),
            ],
        ),
        migrations.CreateModel(
            name='Type2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_title', models.CharField(blank=True, default='EVENT', max_length=20, verbose_name='modal_title')),
                ('h2', models.CharField(max_length=40, verbose_name='h2')),
                ('p', models.TextField(help_text='줄넘기기 : br tag, 강조 : strong tag', verbose_name='p')),
                ('link_url', models.CharField(blank=True, help_text='공란 가능', max_length=1200, verbose_name='link_url')),
                ('link_text', models.CharField(default='Get Started', max_length=20, verbose_name='link_text')),
                ('link_video_url', models.CharField(blank=True, help_text='공란 가능', max_length=1200, verbose_name='link_video_url')),
                ('link_video_text', models.CharField(default='Watch Video', max_length=20, verbose_name='link_video_text')),
                ('bg', models.ImageField(upload_to='images/popup/type2')),
                ('activate', models.BooleanField(default=False, help_text='활성창 1개만 가능')),
            ],
        ),
        migrations.CreateModel(
            name='Type3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_title', models.CharField(blank=True, default='EVENT', max_length=20, verbose_name='modal_title')),
                ('h2', models.CharField(help_text='줄넘기기 : br tag', max_length=40, verbose_name='h2')),
                ('p', models.TextField(help_text='줄넘기기 : br tag, 강조 : strong tag', verbose_name='p')),
                ('link_url', models.CharField(blank=True, help_text='공란 가능', max_length=1200, verbose_name='link_url')),
                ('link_text', models.CharField(default='Book a Table', max_length=20, verbose_name='link_text')),
                ('link_video_url', models.CharField(blank=True, help_text='공란 가능', max_length=1200, verbose_name='link_video_url')),
                ('link_video_text', models.CharField(default='Watch Video', max_length=20, verbose_name='link_video_text')),
                ('img', models.ImageField(upload_to='images/popup/type3')),
                ('activate', models.BooleanField(default=False, help_text='활성창 1개만 가능')),
            ],
        ),
        migrations.CreateModel(
            name='Type4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_title', models.CharField(blank=True, default='EVENT', max_length=20, verbose_name='modal_title')),
                ('h3', models.CharField(help_text='강조 : strong tag', max_length=20, verbose_name='h3')),
                ('h1', models.CharField(max_length=40, verbose_name='h1')),
                ('h2', models.TextField(help_text='줄넘기기 : br tag, 강조 : strong tag', verbose_name='h2')),
                ('link_url', models.CharField(blank=True, help_text='공란 가능', max_length=1200, verbose_name='link_url')),
                ('link_text', models.CharField(default='Get Started', max_length=20, verbose_name='link_text')),
                ('bg', models.ImageField(upload_to='images/popup/type4')),
                ('activate', models.BooleanField(default=False, help_text='활성창 1개만 가능')),
            ],
        ),
        migrations.CreateModel(
            name='Type5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_title', models.CharField(blank=True, default='NOTI', max_length=20, verbose_name='modal_title')),
                ('img', models.ImageField(upload_to='images/popup/type5')),
                ('activate', models.BooleanField(default=False, help_text='활성창 1개만 가능')),
            ],
        ),
    ]
