# flake8: noqa

"""
    Emil Payment Service

    This service directly communicates with the various Payment Service Providers (PSPs)    in order to charge or refund customers. This service will automatically connect to the PSP linked   in your admin configuration; meaning if you configured Stripe, it will automatically create a payment   on Stripe when you create it in Emil.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from eis.payments.api_client import ApiClient

# import Configuration
from eis.payments.configuration import Configuration

# import exceptions
from eis.payments.exceptions import OpenApiException
from eis.payments.exceptions import ApiAttributeError
from eis.payments.exceptions import ApiTypeError
from eis.payments.exceptions import ApiValueError
from eis.payments.exceptions import ApiKeyError
from eis.payments.exceptions import ApiException
