
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-22T14:48:11-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce236bb304b11302a982af2ecb1f8cbb403d09f4",
 "version": "2022.09"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
