# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class V1Mode(str, Enum):
    """
    V1Mode
    """

    """
    allowed enum values
    """
    MODE_UNSPECIFIED = 'MODE_UNSPECIFIED'
    MODE_TEST = 'MODE_TEST'
    MODE_STAGING = 'MODE_STAGING'
    MODE_PROD = 'MODE_PROD'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1Mode from a JSON string"""
        return cls(json.loads(json_str))


