# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class V1RoutingBlockType(str, Enum):
    """
    V1RoutingBlockType
    """

    """
    allowed enum values
    """
    ROUTING_BLOCK_TYPE_UNSPECIFIED = 'ROUTING_BLOCK_TYPE_UNSPECIFIED'
    ROUTING_BLOCK_TYPE_SPEND_CAP = 'ROUTING_BLOCK_TYPE_SPEND_CAP'
    ROUTING_BLOCK_TYPE_AB = 'ROUTING_BLOCK_TYPE_AB'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1RoutingBlockType from a JSON string"""
        return cls(json.loads(json_str))


