
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-28T12:10:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc21336a67334241d1c9a59383084ce453988d4e",
 "version": "2.22.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
