# Generated by Django 5.0.6 on 2024-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0002_alter_cycle_base_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='config_value',
            field=models.BooleanField(default=False),
        ),
    ]
