# Generated by Django 5.0.6 on 2024-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0003_alter_systemconfig_config_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcontrol',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('error', 'Error'), ('delete', 'Delete'), ('standby', 'Stand By')], default='pending', max_length=20),
        ),
    ]
