
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-24T11:35:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "359b502a23c7eb8abbfc0cac8549e1281936ed03",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
