
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-28T16:56:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a716d69a714b95299e05e51f896a7d10dbf3cf3f",
 "version": "2.0.0b42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
