
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-23T14:20:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "333376e970ea47bc3d60df9beadf727661887f55",
 "version": "2024.5.23.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
