
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-23T17:16:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "923bcb5cb7b78e46069a437d482a781a7cea8394",
 "version": "2024.5.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
